// getters
export const GET_LINEUPS = 'squad/GET_LINEUPS'
export const GET_PLAYERS = 'squad/GET_PLAYERS'
export const GET_POSITIONS = 'squad/GET_POSITIONS'
export const GET_FORMATIONS = 'squad/GET_FORMATIONS'
export const GET_NEW_LINEUP = 'squad/GET_NEW_LINEUP'
export const GET_SELECTED_LINEUP = 'squad/GET_SELECTED_LINEUP'
export const GET_GAMES = 'squad/GET_GAMES'
export const GET_CRUD_GAME = 'squad/GET_CRUD_GAME'

// actions
export const FETCH_KVP_USERS = 'squad/FETCH_KVP_USERS'
export const FETCH_LINEUP = 'squad/FETCH_LINEUP'
export const FETCH_LINEUPS_ON_USER = 'squad/FETCH_LINEUPS_ON_USER'
export const FETCH_LINEUP_ON_POST = 'squad/FETCH_LINEUP_ON_POST'
export const FETCH_PLAYERS = 'squad/FETCH_PLAYERS'
export const FETCH_POSITIONS = 'squad/FETCH_POSITIONS'
export const FETCH_FORMATIONS = 'squad/FETCH_FORMATIONS'
export const CREATE_LINEUP = 'squad/CREATE_LINEUP'
export const CREATE_PLAYER = 'squad/CREATE_PLAYER'
export const UPDATE_PLAYER = 'squad/UPDATE_PLAYER'
export const FETCH_GAMES = 'squad/FETCH_GAMES'
export const CREATE_GAME = 'squad/CREATE_GAME'

// mutations
export const SET_LINEUPS = 'squad/SET_LINEUPS'
export const SET_PLAYERS = 'squad/SET_PLAYERS'
export const SET_FORMATIONS = 'squad/SET_FORMATIONS'
export const SET_POSITIONS = 'squad/SET_POSITIONS'
export const SET_SELECTED_LINEUP = 'squad/SET_SELECTED_LINEUP'
export const SET_NEW_LINEUP = 'squad/SET_NEW_LINEUP'
export const SET_PLAYER_TO_LINEUP = 'squad/SET_PLAYER_TO_LINEUP'
export const SET_GAMES = 'squad/SET_GAMES'
export const SET_CRUD_GAME = 'squad/SET_CRUD_GAME'
export const SET_GAME_EVENT = 'squad/SET_GAME_EVENT'
export const CHANGE_GAME_EVENT = 'squad/CHANGE_GAME_EVENT'
export const DELETE_GAME_EVENT = 'squad/DELETE_GAME_EVENT'